import Head from "next/head";
import { Box, Button, IconButton, Typography, useTheme } from "@mui/material";
import DownloadOutlinedIcon from "@mui/icons-material/DownloadOutlined";
import EmailIcon from "@mui/icons-material/Email";
import PersonAddIcon from "@mui/icons-material/PersonAdd";
import PointOfSaleIcon from "@mui/icons-material/PointOfSale";
import TrafficIcon from "@mui/icons-material/Traffic";
import BarChart from "@/components/charts/barChart";
import GeographyChart from "@/components/charts/geographyChart";
import LineChart from "@/components/charts/lineChart";
import Header from "@/components/common/header";
import ProgressCircle from "@/components/common/progressCircle";
import StatBox from "@/components/common/statBox";
import { mockTransactions } from "@/data/mockData";
import { colorTokens } from "@/styles/theme";

export default function Home() {
    const theme = useTheme();
    const colors = colorTokens(theme.palette.mode);

    return (
        <>
            <Head>
                <title>Dashboard</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box
                sx={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    padding: "0 16px",
                    marginBottom: "10px",
                }}
            >
                <Header
                    title="Dashboard"
                    subtitle="Welcome to your dashboard"
                />
                <Box>
                    <Button
                        sx={{
                            backgroundColor: colors.blueAccent[700],
                            color: colors.grey[100],
                            fontSize: "14px",
                            fontWeight: "bold",
                            p: "10px 20px",
                        }}
                    >
                        <DownloadOutlinedIcon sx={{ mr: "10px" }} />
                        Download Report
                    </Button>
                </Box>
            </Box>
            <Box
                sx={{
                    display: "grid",
                    gridAutoRows: "140px",
                    gridTemplateColumns: "repeat(12, 1fr)",
                    gap: "20px",
                    padding: "16px",
                    maxHeight: "80vh",
                    overflow: "auto",
                }}
            >
                <Box
                    sx={{
                        backgroundColor: colors.primary[400],
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        gridColumn: "span 3",
                    }}
                >
                    <StatBox
                        title="12,361"
                        subtitle="Emails Sent"
                        progress={0.75}
                        increase="+14"
                        icon={
                            <EmailIcon
                                sx={{
                                    color: colors.greenAccent[600],
                                    fontSize: "26px",
                                }}
                            />
                        }
                    />
                </Box>
                <Box
                    sx={{
                        backgroundColor: colors.primary[400],
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        gridColumn: "span 3",
                    }}
                >
                    <StatBox
                        title="431,225"
                        subtitle="Sales Obtained"
                        progress={0.5}
                        increase="+21"
                        icon={
                            <PointOfSaleIcon
                                sx={{
                                    color: colors.greenAccent[600],
                                    fontSize: "26px",
                                }}
                            />
                        }
                    />
                </Box>
                <Box
                    sx={{
                        backgroundColor: colors.primary[400],
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        gridColumn: "span 3",
                    }}
                >
                    <StatBox
                        title="32,441"
                        subtitle="New Clients"
                        progress={0.3}
                        increase="+5"
                        icon={
                            <PersonAddIcon
                                sx={{
                                    color: colors.greenAccent[600],
                                    fontSize: "26px",
                                }}
                            />
                        }
                    />
                </Box>
                <Box
                    sx={{
                        backgroundColor: colors.primary[400],
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        gridColumn: "span 3",
                    }}
                >
                    <StatBox
                        title="1,325,134"
                        subtitle="Traffic Inbound"
                        progress={0.8}
                        increase="+43"
                        icon={
                            <TrafficIcon
                                sx={{
                                    color: colors.greenAccent[600],
                                    fontSize: "26px",
                                }}
                            />
                        }
                    />
                </Box>

                <Box
                    sx={{
                        gridColumn: "span 8",
                        gridRow: "span 2",
                        backgroundColor: colors.primary[400],
                    }}
                >
                    <Box
                        sx={{
                            mt: "25px",
                            p: "0 30px",
                            display: "flex",
                            justifyContent: "space-between",
                            alignItems: "center",
                        }}
                    >
                        <Box>
                            <Typography
                                variant="h5"
                                fontWeight="600"
                                color={colors.grey[100]}
                            >
                                Revenue Generated
                            </Typography>
                            <Typography
                                variant="h3"
                                fontWeight="bold"
                                color={colors.greenAccent[500]}
                            >
                                $59,342.320
                            </Typography>
                        </Box>
                        <Box>
                            <IconButton>
                                <DownloadOutlinedIcon
                                    sx={{
                                        color: colors.greenAccent[500],
                                        fontSize: "26px",
                                    }}
                                />
                            </IconButton>
                        </Box>
                    </Box>
                    <Box sx={{ height: "250px", mt: "-20px" }}>
                        <LineChart isDashboard />
                    </Box>
                </Box>
                <Box
                    sx={{
                        gridColumn: "span 4",
                        gridRow: "span 2",
                        backgroundColor: colors.primary[400],
                        overflow: "auto",
                        overflowY: "hidden",
                        "&:hover": {
                            overflowY: "visible",
                        },
                    }}
                >
                    <Box
                        sx={{
                            display: "flex",
                            justifyContent: "space-between",
                            alignItems: "center",
                            borderBottom: `4px solid ${colors.primary[500]}`,
                            color: colors.grey[100],
                            p: "15px",
                        }}
                    >
                        <Typography
                            color={colors.grey[100]}
                            variant="h5"
                            fontWeight="600"
                        >
                            Recent Transactions
                        </Typography>
                    </Box>
                    {mockTransactions.map((transaction, i) => (
                        <Box
                            key={`${transaction.txId}-${i}`}
                            sx={{
                                display: "flex",
                                justifyContent: "space-between",
                                alignItems: "center",
                                borderBottom: `4px solid ${colors.primary[500]}`,
                                p: "15px",
                            }}
                        >
                            <Box>
                                <Typography
                                    color={colors.greenAccent[500]}
                                    variant="h5"
                                    fontWeight="600"
                                >
                                    {transaction.txId}
                                </Typography>
                                <Typography color={colors.grey[100]}>
                                    {transaction.user}
                                </Typography>
                            </Box>
                            <Box color={colors.grey[100]}>
                                {transaction.date}
                            </Box>
                            <Box
                                sx={{
                                    backgroundColor: colors.greenAccent[500],
                                    p: "5px 10px",
                                    borderRadius: "4px",
                                }}
                            >
                                ${transaction.cost}
                            </Box>
                        </Box>
                    ))}
                </Box>

                <Box
                    sx={{
                        gridColumn: "span 4",
                        gridRow: "span 2",
                        backgroundColor: colors.primary[400],
                        p: "30px",
                    }}
                >
                    <Typography variant="h5" fontWeight="600">
                        Campaign
                    </Typography>
                    <Box
                        sx={{
                            display: "flex",
                            flexDirection: "column",
                            alignItems: "center",
                            mt: "25px",
                        }}
                    >
                        <ProgressCircle size={125} />
                        <Typography
                            variant="h5"
                            color={colors.greenAccent[500]}
                            sx={{ mt: "15px" }}
                        >
                            $48,352 revenue generated
                        </Typography>
                        <Typography>
                            Includes extra misc expenditures and costs
                        </Typography>
                    </Box>
                </Box>
                <Box
                    sx={{
                        gridColumn: "span 4",
                        gridRow: "span 2",
                        backgroundColor: colors.primary[400],
                    }}
                >
                    <Typography
                        variant="h5"
                        fontWeight="600"
                        sx={{ p: "30px 30px 0 30px" }}
                    >
                        Sales Quantity
                    </Typography>
                    <Box
                        sx={{
                            height: "250px",
                            mt: "-20px",
                        }}
                    >
                        <BarChart isDashboard />
                    </Box>
                </Box>
                <Box
                    sx={{
                        gridColumn: "span 4",
                        gridRow: "span 2",
                        backgroundColor: colors.primary[400],
                        p: "30px",
                    }}
                >
                    <Typography
                        variant="h5"
                        fontWeight="600"
                        sx={{ mb: "15px" }}
                    >
                        Geography Base Traffic
                    </Typography>
                    <Box
                        sx={{
                            height: "200px",
                        }}
                    >
                        <GeographyChart isDashboard />
                    </Box>
                </Box>
            </Box>
        </>
    );
}
